os: linux
dist: bionic
language: python

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks here -r3 --$LUA
  - export PATH=$PATH:$PWD/here/bin
  - eval `luarocks path --bin`
  - lua -v

install:
  - echo 'Installing runtime dependencies...'
  - luarocks install --only-deps $(find luarocks -name '*-scm-*.rockspec' | sort -g | tail -1)
  - echo 'Installing additional testing dependencies...'
  - luarocks install dromozoa-utf8
  - luarocks install cluacov
  - luarocks install busted
  - luarocks install luacov-coveralls

script:
  - timeout 120 busted -c

after_success:
  - luacov-coveralls -i wcwidth/ -e spec/ -e here/
