language: python
sudo: false

env:
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin
  - eval `luarocks path --bin`
  - lua -v

install:
  - echo 'Installing runtime dependencies...'
  - luarocks install --only-deps wcwidth-scm-*.rockspec
  - echo 'Installing additional testing dependencies...'
  - luarocks install dromozoa-utf8
  - luarocks install cluacov
  - luarocks install busted

script:
  - timeout 120 busted -c

after_success:
  - luacov-coveralls -i wcwidth/ -e spec/ -e here/
