#! /bin/bash
#
# update-tables
# Copyright (C) 2016 Adrian Perez <aperez@igalia.com>
#
# Distributed under terms of the MIT license.
#
set -e

WIDE_URL='http://www.unicode.org/Public/UNIDATA/EastAsianWidth.txt'
ZERO_URL='http://www.unicode.org/Public/UNIDATA/extracted/DerivedGeneralCategory.txt'

# The version numbers of the files above are parsed from the files themselves.
WIDE_VER='(unknown)'
ZERO_VER='(unknown)'

srcdir=$(dirname "$0")

WIDE_FILE="${srcdir}/${WIDE_URL##*/}"
ZERO_FILE="${srcdir}/${ZERO_URL##*/}"

[[ -r ${WIDE_FILE} ]] || wget -c -O "${WIDE_FILE}" "${WIDE_URL}"
[[ -r ${ZERO_FILE} ]] || wget -c -O "${ZERO_FILE}" "${ZERO_URL}"

parse_file_version () {
	local version rest line
	while read -r line ; do
		if [[ -z ${line} || ${line} = \#* ]] ; then
			read -r line rest <<< "${line}"
			if [[ ${rest} = *.txt ]] ; then
				version=${rest}
			elif [[ ${rest} = Date:\ 20* || ${rest} = ©\ 20* ]] ; then
				version="${version}, ${rest}"
			fi
			continue
		fi
	done
	echo "${version}"
}

make_readme () {
	# Pick newest LuaRocks version
	local V=$(find "${srcdir}/luarocks" -name 'wcwidth-[0-9]*.rockspec' \
		| sed 's,^.*/wcwidth-\([0-9\.]\+\).*$,\1,' | sort -g | tail -1)
	sed -e "s+@@WIDE_FILE@@+${WIDE_FILE##*/}+g" \
		-e "s+@@ZERO_FILE@@+${ZERO_FILE##*/}+g" \
		-e "s+@@WIDE_URL@@+${WIDE_URL}+g" \
		-e "s+@@ZERO_URL@@+${ZERO_URL}+g" \
		-e "s+@@WIDE_VER@@+${WIDE_VER}+g" \
		-e "s+@@ZERO_VER@@+${ZERO_VER}+g" \
		-e "s+@@LUAROCKS_VER@@+${V}+g"
}

WIDE_VER=$(parse_file_version < "${WIDE_FILE}")
ZERO_VER=$(parse_file_version < "${ZERO_FILE}")
make_readme < "${srcdir}/README.md.in" > "${srcdir}/README.md"

cat "${WIDE_FILE}" "${ZERO_FILE}" | "${srcdir}/generate-tables" -p"${srcdir}/wcwidth"
